spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false


---
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false


