spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在的包
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mybatis 映射文件
spring:
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: k646715739
    dbcp2:
     min-idle: 5
     initial-size: 5                                       # 初始化连接数
     max-total: 5                                          # 最大连接数
     max-wait-millis: 200
  profiles: dev
eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-provider-dept-8001
    prefer-ip-address: true
info:
 app.name: atguigu-microservicecloud
 companyname: www.atguigu.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在的包
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mybatis 映射文件
spring:
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: k646715739
    dbcp2:
     min-idle: 5
     initial-size: 5                                       # 初始化连接数
     max-total: 5                                          # 最大连接数
     max-wait-millis: 200
  profiles: test
eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-provider-dept-8001
    prefer-ip-address: true
info:
 app.name: atguigu-microservicecloud
 companyname: www.atguigu.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$